molecule: alanine

simulation:
  state: c5
  forcefield:
    - amber14-all
    - tip3pfb
  integrator:
    type: Lagevin
    temperature: 300
    pico: 1
    femto: 1
  platform:
    type: OpenCL
  properties:
    precision: mixed

reporter:
  time: 100
  dcd:
    use: True
    reportInterval: 10
  stdout:
    use: True
    reportInterval: 10
  csv:
    use: True
    reportInterval: 10

